version: '3.1'
services:
  watcher:
    image: 192.168.1.10:4000/remote:latest
    restart: always
    volumes:
      - /data/apps/remote/:/db
      - /data/nfs/seedbox/incoming:/watch
    env_file:
      - ./.env
    command: python -u remote/watcher.py
  web:
    image: 192.168.1.10:4000/remote:latest
    restart: always
    volumes:
      - /data/apps/remote/:/db
      - /data/nfs/seedbox/incoming:/watch
      - /data/movies:/movies
    env_file:
      - ./.env
    ports:
      - 8000:8000
    command: python -u -m flask run --host 0.0.0.0 --port 8000
