version: '3.1'
services:
  web:
    image: remote:latest
    volumes:
      - /tmp/remote:/tmp/remote
      - /data/nfs/seedbox/incoming:/watch
    environment:
      - DB_DIR=/tmp/remote
      - WATCH_DIR=/watch
